### ISSUE TITLE
Background Color of Bash Indicator

### ISSUE THREAD

**Issue by Phidelux** [brujoand/sbp#26] opened 2016-03-24 11:02 UTC
The Background Color of the bash indicator (second line) is not transparent but black.

**Comment by brujoand** [comment] 2016-03-24 11:10
Interesting. Could you provide the exact output of echoing $PS1?

**Comment by Phidelux** [comment] 2016-03-24 11:29
Here you go:

`\n\[\]\[\] awilhelm \[\]\[\]\[\]\[\] ~ \[\]\[\]\[\] \[\]\[\]\[\]\[\] 12:28 \[\e[00m\]\n\[\]\[\] ➜ \[\e[00m\]`

**Comment by brujoand** [comment] 2016-04-01 06:27
I'm not sure what's causing this. My initial thought was that there was something wrong with color generation. But I think that's in the clear. Since my PS1 looks exactly like yours, I'm starting to wonder if this might be related to byte length vs char length. Is your LANG variable set to some variant of UTF-8?

**Comment by dflock** [comment] 2016-04-02 07:51
```
echo $LANG

en_CA.UTF-8

echo $PS1

\n\[\]\[\] duncan \[\]\[\]\[\]\[\]\[\]\[\] ~ \[\]\[\]\[\]\[\] bin \[\]\[\]\[\]\[\] sbp \[\]\[\]\[\]\[\] master u= \[\]\[\]\[\]\[\] \[\]\[\]\[\]\[\] last: 0m 0s \[\]\[\]\[\]\[\] 00:49:08 \[\e[00m\]\n\[\]\[\] ➜ \[\e[00m\]
```

Looks fine, though:

![image](https://cloud.githubusercontent.com/assets/47756/14225140/11ee13fe-f86d-11e5-9f86-7274bd502beb.png)

**Comment by Phidelux** [comment] 2016-04-04 13:50
Having this issue on both laptops and my desktop. All using _en_US.UTF-8_ in _$LANG_.

**Comment by brujoand** [comment] 2016-04-05 07:35
I'm at at a loss to reproduce this. Would you mind posting a full width screenshot of your prompt @Phidelux ? And is this bug irrelevant to which path / plugins are active?

**Comment by xHN35RQ** [comment] 2016-06-14 07:50
Here's the answer: https://github.com/arialdomartini/oh-my-git#with-bash-the-last-symbol-looks-very-bad-like-this

**Comment by brujoand** [comment] 2016-06-14 07:56
Is this still an issue after the latest merge? Iirc the way this is handled now is to reset all colors, then set the foreground.

**Comment by xHN35RQ** [comment] 2016-06-14 08:04
Yes, it was still an issue, I had black backgrounds behind the outside arrows, and the prompt_ready arrow had a black background. The suggestion in the link fixed the issue.

**Comment by ffjia** [comment] 2016-07-20 12:47
If I remember correctly, there's no such problem, at least several months ago. I encountered same issue after running git pull, so it could be introduced by new pull request?

**Comment by brujoand** [comment] 2018-03-31 13:18
Sorry I forgot about this one. It is resolved now on iTerm/osx. Anyone on linux who could confirm?

**Comment by dflock** [comment] 2018-04-02 20:47
Looks fine to me on linux - but then it always has.

**Comment by brujoand** [comment] 2018-04-04 08:04
Cool thanks. I think this bug is only revealed if the user applies some color theme to the terminal. Closing until proven wrong then 👍

**Closed by brujoand** 2018-04-04 08:04 UTC
Labels: bug
